### ISSUE TITLE
Installation/Import problems

### ISSUE THREAD

**Issue by OskarBergmann** [fau-advanced-separations/CADET-Process#1]
Hi,

the installation from git works fine (Windows) but when I try to import the module I get:
in ...installation path\common\settings.py, line 22, in <module>
repo = git.Repo(ROOT_DIR.parent)

File ... \git\repo\base.py raise InvalidGitRepositoryError(epath)
"InvalidGitRepositoryError: C:\...installation path...\CADET-Process-master".

I read a solution can be to do
git init 
in the Cadet-Process-master directory, after which a different error occurs: during the import in settings.py sha  = repo.head.object.hexsha is trying to execute but results in the error

Reference at 'refs/heads/master' does not exist

I do not have this issue with other packages.
Am I missing something?

Thanks :)

**Comment by schmoelder** [comment]
Hi Oskar,

I have to admit, the installation process is still a mess. I'm aware of this problem and I have already planned to redesign the entire installation procedure (and fix some other issues).

For now, these are the steps you need to take:
- I inadvertently assumed that the code was always downloaded by git ''cloning". This way, the last commit hash can be added as meta information in the optimization results. If you just download the zip file, it can obviously not find that repository. So for now, please clone using git bash.
- Make sure, CADET is installed correctly (see https://github.com/modsim/CADET) and enter the path in the settings.json file.
- In Linux, I used a RAM disk for temporary files. As far as I know, this does unfortunately not work under Windows. So you also need to provide another path to the 'tempdir' in the settings.json. It really does not matter where, it just needs to be a location with write access,  where internally some files are created for running the simulation with CADET which are then also deleted again.

I hope this way you can get it to run. If any issues remain, I'm happy to provide more help.

I should have worked on it earlier and I'm sorry for the inconvenience. CADET-Process is still under heavy development and I'm learning a lot as I go.

**Comment by OSBR-alt** [comment]
Hi,

thanks for your answer. The problem with the git repository could be resolved thanks to your instructions but something seems to be wrong with the tempdir directory. I did as you suggested and entered a random path (this is how my settings.json file looks:
{
    "project_directory": "",
    "cadet_path": "C:\\Users\\OSBR\\Documents\\Anaconda\\cadet4.0.1-win10-x64\\cadet\\bin\\cadet-cli.exe",
    "LOG_LEVEL": "INFO",
    "tempdir": "C:\\Users\\OSBR\\Documents\\Anaconda\\CAD_case"
}
 
But h5py throws the error

  File "h5py\h5f.pyx", line 108, in h5py.h5f.create

OSError: Unable to create file (unable to open file: name = 'C:\Users\OSBR\Documents\Anaconda\CAD_case\tmp4cd4qcg7.h5', errno = 13, error message = 'Permission denied', flags = 13, o_flags = 302).

I have write access in that folder (e.g. open(r'C:\Users\OSBR\Documents\Anaconda\CAD_case\test.txt',"w") works fine).
Any ideas?

**Comment by schmoelder** [comment]
Hi Oscar,
I simplified the whole installation process and removed the need for the settings.json file.
Now, the CADET process simulator needs to be passed the location of the cadet installation in its __init__ method. (See the examples). If you need help installing CADET itself, please see [here](https://cadet.github.io/getting_started/installation.html).
I also tried to remove the need for a git repository and made the tempfile procedure platform independent. Apparently the way I had it implemented was only working on Linux.
I hope this fixes the problem. Let me know if there are more issues!

**Comment by OskarBergmann** [comment]
Hi schmoelder,

I will look into it soon, thanks for making it available for Windows too!

**Comment by schmoelder** [comment]
CADET-Process can now be installed with pip
```
pip install CADET-Process
```
Please ensure that CADET is also installed. For information, see cadet.github.io
