### ISSUE TITLE
CI for MacOS fails

### ISSUE THREAD

**Issue by ronald-jaepel** [fau-advanced-separations/CADET-Process#134]
`macos-latest` used to be `macosx-10.9-x86_64` and has been replaced with `macos-14-arm64`. `CADET`-Core isn't available for arm mac ([conda-forge](https://anaconda.org/conda-forge/cadet)) yet.

Relevant issue in [CADET](https://github.com/modsim/CADET/issues/192)

**Comment by schmoelder** [comment]
Closing, since this needs to be solved upstream.
