### ISSUE TITLE
Colloidal Isotherm

### ISSUE THREAD

**Issue by abe-martin** [fau-advanced-separations/CADET-Process#14]
Is it possible to use the Collodial isotherm in CADET Process?  I see references to it in the main CADET package under the name of MULTI_COMPONENT_COLLOIDAL, but I don't see anything matching that here.

**Comment by schmoelder** [comment]
Hi, currently it's undocumented because it's still missing a (tricky) Jacobian. See PR over [here](https://github.com/modsim/CADET/pull/85).
Closing since this it's an issue of CADET-Core and not necessarily of CADET-Process. Feel free to continue over at the other Repo! :)
