### ISSUE TITLE
ImportError: cannot import name 'FixedNoiseGP' from 'botorch.models.gp_regression'

### ISSUE THREAD

**Issue by ronald-jaepel** [fau-advanced-separations/CADET-Process#174]
Users report
`ImportError: The AxInterface class could not be imported. This may be because the 'ax' package, which is an optional dependency, is not installed. To install it, run 'pip install CADET-Process[ax]'`

which is caused by 
`ImportError: cannot import name 'FixedNoiseGP' from 'botorch.models.gp_regression' (/Users/angelamoser/miniconda3/envs/ax-env/lib/python3.12/site-packages/botorch/models/gp_regression.py)`

which is caused by BoTorch removing the deprecated `FixedNoiseGP`. We should replace it with `SingleTaskGP`.

https://github.com/pytorch/botorch/pull/2536

**Comment by flo-schu** [comment]
I'm about to fix this in #98

**Comment by schmoelder** [comment]
Fixed in #179
