### ISSUE TITLE
Add a Release Guide for CADET-Process

### ISSUE THREAD

**Issue by hannahlanzrath** [fau-advanced-separations/CADET-Process#183]
We should add a Release Guide to navigate new releases if it doesn't exist already. We can use the [CADET-Core Release Guide](https://github.com/cadet/CADET-Core/blob/0887fcb368bf99d97415bcacb27c81a44ba63efd/doc/developer_guide/release_new_version.rst) as a rough template. Besides being part of the documentation it should be nice, to create an issue template from it that can be used for new releases.

**Comment by schmoelder** [comment]
Currently, the release guide lives in the [Forum](https://forum.cadet-web.de/t/how-to-make-a-new-cadet-process-release/847) but I agree, we should migrate it.
