### ISSUE TITLE
Update FixedNoiseGP in optimization to new Api

### ISSUE THREAD

**Issue by daklauss** [fau-advanced-separations/CADET-Process#199]
As stated in https://botorch.org/v/0.9.5/api/_modules/botorch/models/gp_regression.html#FixedNoiseGP, FixedNoiseGP is deprecated and will be removed with v0.12. 
```axAdapter.py``` still uses the old api, leading to a crash while importing/using the module.

Line 22:
```from botorch.models.gp_regression import FixedNoiseGP```

**Comment by schmoelder** [comment]
Isn't this already fixed in https://github.com/fau-advanced-separations/CADET-Process/pull/179?
