### ISSUE TITLE
Implement a bayesian opimization algorithm for CADET-process based on Ax/BoTorch

### ISSUE THREAD

**Issue by flo-schu** [fau-advanced-separations/CADET-Process#30]
I would launch a branch/PR based on this issue. @schmoelder Let's collect some things that need to be done for this feature.

- [x] implement a minimal working example based on one of the toy problems of Ax/Botorch in Cadet process
- [ ] write a unit-test for this example
- [ ] write documentation for new feature
- [ ] write the interface for Ax

**Comment by schmoelder** [comment]
Sounds good to me!

**Comment by flo-schu** [comment]
I have created a scripted minimal working example for BO with Ax on one of the example datasets. It works nicely. If you want to try it check out the new branch. Next steps would be 

- to build the adapter
- distribute the code currently in `AxAdapter.py` to tests and the actual adapter. This means from now I'd work on the test cases and improve the adapter step-by-step
