### ISSUE TITLE
Standard initialization of column model leads to a stall during simulation

### ISSUE THREAD

**Issue by maruedt** [fau-advanced-separations/CADET-Process#32]
I have been struggling with a stalling simulation and by now, I think that the issue is caused by me not initializing the solid and liquid phase concentrations in a `LumpedRateModelWithPores` and a `StericMassAction` isotherm. Just to summarize, during debugging, I made following observations:

1. If I run the model with the correct initialization, everything works smoothly and as expected. Below a code snipped of the simulation part:

```python
column = generate_column(1, characteristic_charge=4.2, initial_conc=True)   # initialize column
sim_result = simulate_process(column, timeout=30)  # run simulation
# since it worked lets plot the chromatograms
plot_sim_results(sim_result)
```
--> runs in 2-3 s and chromatogram looks fine

2. If I do not initialize the initial concentrations and run the simulation, the simulation does not terminate in a reasonable time. Might be difficult to treat numerically (?). For sure, CADET-Process calls the cadet-cli, however the cadet-cli does not terminate within a reasonable time. For the example below I set a timeout after 30 s.
```python
column = generate_column(1, characteristic_charge=4.2, initial_conc=False) # initialize column
sim_result = simulate_process(column, timeout=30)  # run simulation with timeout of 30 s
```
--> stalling simulation

3.  Now the surprising/misleading bit: if the characteristic charge is set to an integer value, it works anyway!
```python
column = generate_column(1, characteristic_charge=4, initial_conc=False)
sim_result = simulate_process(column)
```
--> runs in 2-3 s

So, maybe as a first question: is my interpretation correct that a missing initialization of the simulation may lead to such a behavior? If so, could this behavior be changed or would this cause issues for other parts of the code?

As is, the debugging is quite troublesome. The first step is to realize that the simulation is stalling. Then, the interpretation of the stalling simulation is difficult and the different behavior between integer and non-integer values of the characteristic charge adds to the confusion. My initial idea was if it would be reasonable to include `c` and `_q` in the required parameters and remove the `default=0` from the class definition. Any thoughts on this?

**Comment by schmoelder** [comment]
Hi,

could you please provide a full reproducible example for this issue? It's hard to debug without the full picture.

One thing that I can already say, consistent initialization is generally very hard, especially if you use something like the SMA isotherm. For this, I recommend always using some initial concentration for the bulk/particle pore space. For the solid concentration it's even required since we assume the resin is always fully loaded. So best set $q_0 = 0$

Why it works for an integer characteristic charge, I can only speculate. Probably it has to do with the parameter being in the exponent s.t. any negative concentrations that might occur (small values between 0 can always occur) are made positive for an even characteristic charge. This might smooth out the problem during initialization. But as I mentioned, this is only speculation.

Hope this helps!

Johannes

**Comment by schmoelder** [comment]
I just realised there was a typo. $q_0(t=0)$ should be $\Lambda$ (i.e. the resin capacity), not $0$! Already fixed it above...

**Comment by maruedt** [comment]
Hi Johannes,

Sorry, I did not want to include the whole script since it is quite lengthy due to the initialization. But please see below:

```python
import numpy as np
from CADETProcess.processModel import ComponentSystem
from CADETProcess.processModel import LumpedRateModelWithPores
from CADETProcess.processModel import StericMassAction
from CADETProcess.processModel import Inlet, Outlet
from CADETProcess.processModel import FlowSheet
from CADETProcess.processModel import Process
from CADETProcess.simulator import Cadet
import matplotlib.pyplot as plt
import multiprocessing
import psutil

def generate_column(n_comps, characteristic_charge=4, initial_conc=True):
    "Generate standard column with SMA isotherm and n components"
    components = [str(i) for i in range(n_comps)]
    components.insert(0, 'Salt')
    
    # define components
    component_system = ComponentSystem(components)

    # isotherm
    binding_model = StericMassAction(component_system)
    binding_model.is_kinetic = False
    # vary adsorption rates for different components
    binding_model.adsorption_rate = np.linspace(0.1, 0.5, num=n_comps+1).tolist()
    binding_model.adsorption_rate[0] = 1.0
    binding_model.desorption_rate = np.ones(n_comps+1).tolist()
    binding_model.capacity = 822.5
    binding_model.steric_factor = np.ones(n_comps+1).tolist()
    # set the characteristic charge for all components except salt to 1
    binding_model.characteristic_charge = (characteristic_charge*np.ones(n_comps+1)).tolist()
    binding_model.characteristic_charge[0] = 0

    # column
    column = LumpedRateModelWithPores(component_system, 'column')
    column.binding_model = binding_model
    column.length = 0.1
    column.diameter = 0.0077
    column.bed_porosity = 0.36
    column.particle_radius = 34e-6
    column.particle_porosity = 0.85
    column.axial_dispersion = 1.5e-6
    column.film_diffusion = (5e-7*np.ones(n_comps+1)).tolist()
    column.film_diffusion[0] = 2e-6
    
    if initial_conc:
        column.c = np.zeros(n_comps+1).tolist()
        column.c[0] = 20
        column.q = np.zeros(n_comps+1).tolist()
        column.q[0] = binding_model.capacity
    return column

def generate_process(column):
    "Generate standard process with a column"
    component_system = column.component_system
    n_comps = component_system.n_comp-1
    
    # flow sheet
    inlet = Inlet(component_system, name='inlet')
    inlet.flow_rate = 8.33e-09

    outlet = Outlet(component_system, name='outlet')
    flow_sheet = FlowSheet(component_system)
    flow_sheet.add_unit(inlet)
    flow_sheet.add_unit(column)
    flow_sheet.add_unit(outlet)

    flow_sheet.add_connection(inlet, column)
    flow_sheet.add_connection(column, outlet)
    
    # process
    flow_rate = 8.33e-09
    sample_volume = 50e-9
    wash_volume = 15e-6
    gradient_volume = 18.8e-6 
    strip_volume = 10e-6
    conc_salt_start = 20
    conc_salt_end = 1020

    wash_start = sample_volume/flow_rate
    gradient_start = sample_volume/flow_rate + wash_volume/flow_rate
    strip_start = sample_volume/flow_rate + wash_volume/flow_rate + gradient_volume/flow_rate 
    t_cycle = sample_volume/flow_rate + wash_volume/flow_rate + gradient_volume/flow_rate + strip_volume/flow_rate

    slope = (conc_salt_end-conc_salt_start)/(gradient_volume/flow_rate)

    process = Process(flow_sheet, 'LGE_18_8mL')
    process.cycle_time = t_cycle
    
    load_conc = (0.2*np.ones(n_comps+1)).tolist()
    load_conc[0] = conc_salt_start
    _ = process.add_event('load', 'flow_sheet.inlet.c', load_conc, 0)
    wash_conc = np.zeros(n_comps+1).tolist()
    wash_conc[0] = conc_salt_start
    _ = process.add_event('wash', 'flow_sheet.inlet.c', wash_conc, wash_start)
    
    gradient_conc = np.zeros([n_comps+1, 2])
    gradient_conc[0,:] = np.array([conc_salt_start, slope])
    _ = process.add_event(
        'grad_start',
        'flow_sheet.inlet.c',
        gradient_conc.tolist(),
        gradient_start
    )
    conc_strip = np.zeros(n_comps+1).tolist()
    conc_strip[0] = conc_salt_end
    _ = process.add_event('strip', 'flow_sheet.inlet.c', conc_strip, strip_start)
    return process

# some functions to run simulation in a parallel process with timeout
def generate_simulation_runner(column):
    "Return function handle to run simulation"
    process = generate_process(column)
    simulator = Cadet()
    simulation_runner = lambda: simulator.simulate(process)
    return simulation_runner

def kill_parent_and_children(parent_pid):
    "Kill parent_process & children"
    parent = psutil.Process(parent_pid)
    for child in parent.children(recursive=True):  # or parent.children() for recursive=False
        child.kill()
    parent.kill()
    
def simulate_process(column, timeout=10):
    "Simulate and kill simulation if not successful"
    run_simulation = generate_simulation_runner(column)
    p = multiprocessing.Process(target=run_simulation)
    p.start()

    # Wait for timeout seconds or until process finishes
    p.join(timeout)

    # Raise error if process did not finish in 10 s
    if p.is_alive():
        kill_parent_and_children(p.pid)
        print('Simulation does not finish!!')
    else:
        print('Simulation finished')
        process = generate_process(column)
        simulator = Cadet()
        result = simulator.simulate(process)
        return result
    
def plot_sim_results(sim_result):
    c_out = sim_result.solution.column.outlet.total_concentration_components
    t_out = sim_result.solution.column.outlet.time

    plt.plot(t_out, c_out[:, 0])
    plt.plot(t_out, c_out[:, 1:]*2e5)

    plt.xlabel('Time / s')
    plt.ylabel('Salt concentration / mM\nProtein concentration / 2e5 *mM')

column = generate_column(1, characteristic_charge=4.2, initial_conc=True)
sim_result = simulate_process(column, timeout=30)
# since it worked lets plot the chromatograms
plot_sim_results(sim_result)

column = generate_column(1, characteristic_charge=4.2, initial_conc=False)
sim_result = simulate_process(column, timeout=30)

# now the surprising/misleading bit: if the characteristic charge is set to an integer value, it works anyway!
column = generate_column(1, characteristic_charge=4, initial_conc=False)
sim_result = simulate_process(column)
```

The code is an adjusted version of the Yamamoto tutorial.

**Comment by schmoelder** [comment]
Thanks.

as I mentioned, consistent initialization of the SMA is hard. Please use some non-zero initial salt concentration for the liquid phase. It can be very small (e.g. 1e-6 mM) but it makes it easier for the solver in CADET-Core.

We could consider doing that by default to prevent crashes but it's a slippery slope because then it's not 100 % clear anymore what happens under the hood. I might consider adding a warning in CADET-Process if a 0-concentration is detected.
Or, even better, we could have a look at the solver itself but that's certainly not my area of expertise. I can bring it up in the next dev-meeting, though.

**Comment by maruedt** [comment]
Hi Johannes,

Thanks for the feedback. Hope it is ok, if I propose also one potential solution although you already closed the issue. Looking at `unitOperation.LumpedRateModelWithPores`, the default values of `c` and `_q` of a newly instantiated class are currently 0:

https://github.com/fau-advanced-separations/CADET-Process/blob/29eb5cc463892b4e969dcd07f3cd9fb968bcce23/CADETProcess/processModel/unitOperation.py#L822-L824

For me this is implicit assumption on the initial conditions of the system. Having a concentration of 0 might often be ok but certainly not always (:grinning: basically the problem which I just had in the beginning of the week). Now, I was thinking if it made sense to include the two values into `_required_parameters`. If so, the user will get a direct feedback why the simulation is not working. Looking code written on the user-side, it might also be a bit more pythonic since such a change will force users to state the initial conditions explicitly instead of implicitly.

Disadvantages is that this is a breaking change potentially causing an impact on other parts of the code and for users.

Would be interesting to get your feedback.

**Comment by schmoelder** [comment]
Yeah, I see your point. However, CADET-Process is just a wrapper around CADET-Core and I tried to follow its default values.
For reference, in eq (9), it states that by default, initial concentrations are $0$ (https://cadet.github.io/master/modelling/unit_operations/general_rate_model.html#general-rate-model-model).

But again, I'll bring it up in our next dev call.

**Comment by maruedt** [comment]
Cool, thanks!

**Comment by schmoelder** [comment]
Also thanks to you for taking your time and giving feedback. CADET-Process is definitely still a bit rough on the edges but it's getting there (I hope). So please let me know if you have any issues or ideas on how to improve it.
