### ISSUE TITLE
Adding library to Code Library Search

### ISSUE THREAD

**Issue by mswoff** [fau-advanced-separations/CADET-Process#49]
I wanted to let you know that users of our Code Library Search Chatgpt plugin has requested we support the CADET-process Python library. Unless we hear otherwise from you, we’ll add support for your Python library (no action required from your team).

The plugin let's users get library specific coding help by analyzing your library's codebase.

If you want to get in touch about any concerns or offering AI based support directly on your forum/website, please email me at mason@salv.ai.

**Comment by schmoelder** [comment]
Closing since there's nothing to do here.
