### ISSUE TITLE
equality constraints conflict with hopsy

### ISSUE THREAD

**Issue by flo-schu** [fau-advanced-separations/CADET-Process#50]
## tolerance (eps) in equality constraints

- Currently, when equality constraints are specified in an optimization problem, `x0` needs to be specified that follows the constraints. Hopsy can generate a candidate but this is expensive. If the tolerance given to equality constraints is low (e.g. `eps = 1e-10`) then hopsy takes forever to find feasible candidates. With decreasing tolerance, it becomes easier for hopsy but the accuracy for the solution is obiously decreased

```py
optimization_problem.add_linear_equality_constraint(['var_0', 'var_1'], [1.0,  2.0], 8, eps=1e-10)
```

- with scipy based optimizers this problem can be circumvented by specifying an x0 that satisfies the constraints. Then `eps = 1e-10` will lead to accurate solutions
- for the genetic algorithm this is currently not ideal. It will solve but there will be some inaccuracy

The ideal solve for this is support of hopsy for equality constraints

##

**Comment by schmoelder** [comment]
As a workaround, add two linear constraints to hopsy (using the specified eps).

E.g. something like the following?

```
import numpy as np

A = np.array([[]]).reshape(0, 2)
b = np.array([])

A_eq = np.array([[1.0, 1.0]])
b_eq = np.array([2.0])

eps_eq = np.array([1e-6])

for a, b_eq_i, eps in zip(A_eq, b_eq, eps_eq):
    A = np.vstack((A, a))
    b = np.hstack((b, b_eq_i + eps))

    A = np.vstack((A, -a))
    b = np.hstack((b, -b_eq_i + eps))

print(A)
print(b)
```

Disclaimer, I did not test this. Hope, I didn't screw up the signs! :sweat_smile:

**Comment by schmoelder** [comment]
[hopsy v1.3.0](https://pypi.org/project/hopsy/1.3.0/) now supports exposes equality constraints so we could start implementing this in the optimization module.

**Comment by schmoelder** [comment]
Was added in 580a84e351c9053c569517d834c8ce07e92283f8
